version: '3.3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    command: node server.js
    ports:
      - '8080:8080'
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api
    command: bash -c "forever --watch src/index.js"
    ports:
      - '3000:3000'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "hunter2"
      MYSQL_ROOT_PASSWORD: hunter2
    ports:
      - '3306:3306'
    expose:
      - '3306'